// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbgvcgrkfxlihcvqssah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpiZ3ZjZ3JrZnhsaWhjdnFzc2FoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4MjYyMjMsImV4cCI6MjA2MTQwMjIyM30.ea1ZA2D-Qey33Vo-cb1BSyT6SFbV9nsxezJnle__K-Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);